# -*- coding: utf-8 -*-
"""Sr_SE_JuanMunthe_Technical Assessment_20-01-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bp608kS51CuRfuI2UzRIhbCG3JPn4oCd
"""

def deret_aritmatika(N):
    # Awal bilangan (a) = 2, beda (d) = 3
    a = 2
    d = 3
    deret = []

    # Menghasilkan deret aritmatika dengan N jumlah
    for i in range(N):
        deret.append(a + i * d)

    return deret

# Contoh penggunaan
N = int(input("Masukkan jumlah deret: "))
hasil = deret_aritmatika(N)
print(", ".join(map(str, hasil)))